Dgroupproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from purchaseapp.views import (
    CreateCheckoutSessionView,
    ProductTopPageView,
    PurchaseCheck,
    SuccessPage,
    CancelPageView,
    stripe_webhook,
    cancel_checkout,
)
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dgroupapp.urls')),
    path('', include('purchaseapp.urls')),
    path('', include('delivery.urls')),
    path('', include('foods.urls')),
    path('', include('adminmenu.urls')),
    path('dgroupLogin/', include('dgroupLogin.urls', namespace='dgroupLogin')),
    path('', include('dgrouinquiry.urls')),
    path('stripe/', ProductTopPageView.as_view(), name="product-top-page"),
    path('stripe/create-checkout-session/', CreateCheckoutSessionView.as_view(), name="create-checkout-session"),
    path('stripe/purchasecheck', PurchaseCheck, name='purchasecheck'),
    path('stripe/success/', SuccessPage, name='success'),
    path('stripe/cancel/', cancel_checkout, name="cancel"),
    path('stripe/cancel/template', CancelPageView.as_view(), name='canceltemplate'),
    path('webhook2/', stripe_webhook, name="webhook"),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="pw_reset.html"), name='password_reset'),
    path('password_reset/done', auth_views.PasswordResetDoneView.as_view(template_name="pw_reset_sent.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="pw_reset_form.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="pw_reset_done.html"), name='password_reset_complete'),
]


# urlpatternsにmediaフォルダのURLパターンを追加
urlpatterns += static(
    # MEDIA_URL = 'media/'
    settings.MEDIA_URL,
    # MEDIA_ROOTにリダイレクト
    document_root=settings.MEDIA_ROOT
)

dgroupapp/urls.py
from django.urls import path,include
from .views import IndexView, LoginView, LogoutView, SuperuserOnlyView
from .import views

app_name = 'dgroupapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('superuser-only/', SuperuserOnlyView.as_view(), name='superuser_only'),
    path('contact/', include('dgrouinquiry.urls')),
    path('switch_account/', views.switch_account, name='switch_account'),
    path('teams/', views.TeamsView.as_view(), name='teams'),  
    path('privacy/', views.PrivacyView.as_view(), name='privacy'),
    path('convenience/', include('Convenience.urls')),
    path('profile/', views.profile, name='profile'),
    path('edit_address/', views.edit_address, name='edit_address'),
    path('address_update_complete/', views.address_update_complete, name='address_update_complete'),
    path('category/<int:category_id>/', views.category_view, name='category_view'),
    path('new-arrivals/', views.NewArrivalsView.as_view(), name='new_arrivals'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('about/', views.AboutView.as_view(), name='about'), 
    
]
#http://127.0.0.1:8000/convenience/register/

foods/urls.py
from django.urls import path
from .import views

app_name = 'foods'

urlpatterns = [
    path('food_input/', views.FoodCreateView.as_view(), name='food_input'),
    path('food_delete/', views.FoodDeleteListView.as_view(), name='food_delete_list'), 
    path('food_delete/<int:pk>/', views.FoodDeleteView.as_view(), name='food_delete'),
    path('food_update/<int:pk>', views.FoodUpdateView.as_view(), name='food_update'),
]

purchaseapp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'purchaseapp'

urlpatterns = [
    path('cart/<int:user>', views.CartView.as_view(), name='cart'),
    path('cart/<int:pk>/delete', views.PurchaseDeleteView.as_view(), name='purchase_delete'),
    path('cart/deletesuccess/<str:stripe_product_id>', views.DeleteSuccess, name="deletesuccess"),
    path('cart/purchase/<int:user>', views.PurchaseView.as_view(), name='purchase'),
    path('cart/<int:pk>/detail', views.DetailView.as_view(), name='detail'),
    path('buy/<int:pk>', views.BuyView.as_view(), name='buy'),
    path('buy/buysuccess/<str:stripe_product_id>', views.BuySuccess, name='buysuccess'),
    path('cart/over/<int:pk>', views.OverView.as_view(), name='over'),
    path('cart/overback', views.Overback, name='overback'),
    path('cart/overdelete/<str:stripe_product_id>', views.OverDelete, name='overdelete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

purchaseapp/models.py
from django.db import models
from dgroupLogin.models import CustomUser
from django.utils import timezone
from django.utils.timezone import now
from datetime import timedelta


class CartPost(models.Model):
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.CASCADE)
    stripe_product_id = models.CharField(verbose_name="商品ID", max_length=100)
    aitemimage = models.ImageField(verbose_name='商品の写真', upload_to='photos')
    category = models.CharField(verbose_name='カテゴリー', max_length=100)
    aitemname = models.CharField(verbose_name='商品名', max_length=200)
    price = models.IntegerField(verbose_name='価格')
    stock = models.IntegerField(verbose_name='数量')
    stockminus = models.IntegerField(verbose_name='削除数量', default=1)
    shelf = models.DateField(verbose_name='賞味期限')
    allergy = models.CharField(verbose_name='アレルギー', max_length=150)
    added_at = models.DateTimeField(verbose_name='追加日時', auto_now_add=True)

    def __str__(self):
        return self.aitemname

    def is_expired(self):
        expiration_time = self.added_at + timedelta(minutes=30)
        return timezone.now() > expiration_time


class OrderPost(models.Model):
    DELIVERY_CHOICES = [
        ('standard', '通常配送'),
        ('express', '速達配送'),
    ]

    PAYMENT_METHOD = [
        ('credit', 'クレジットカード決済'),
        ('cod', '代金引換'),
    ]

    ordernumber = models.IntegerField(verbose_name='注文番号')
    aitem = models.IntegerField(verbose_name='商品数')
    price = models.IntegerField(verbose_name='支払額')
    payment = models.CharField(verbose_name='支払方法', max_length=100, choices=PAYMENT_METHOD)
    user = models.CharField(verbose_name='ユーザー', max_length=100)
    address = models.CharField(verbose_name='住所', max_length=100)
    postal_code = models.CharField(verbose_name='郵便番号', max_length=7, blank=True, null=True)
    delivery_method = models.CharField(max_length=10, choices=DELIVERY_CHOICES, default='standard')
    ordertime = models.DateTimeField(verbose_name='注文日時', auto_now_add=True)
    
    shipped = models.BooleanField(default=False, verbose_name='配送済み')  # 配送完了フラグ
    shipped_date = models.DateTimeField(null=True, blank=True, verbose_name='配送日時')  # 配送日時
    def __str__(self):
        return self.user


class OrderAitemPost(models.Model):
    ordernumber = models.IntegerField(verbose_name='注文番号')
    aitemname = models.CharField(verbose_name='商品名', max_length=100)
    aitemprice = models.IntegerField(verbose_name='価格')
    quantity = models.PositiveIntegerField(verbose_name='数量')
    def __str__(self):
        return self.aitemname


class Product(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=255, blank=True, null=True)
    stripe_product_id = models.CharField(max_length=100)
    file = models.FileField(upload_to="photos", blank=True, null=True)
    def __str__(self):
        return self.name


class Price(models.Model):
    product = models.ForeignKey(Product, related_name='Prices', on_delete=models.CASCADE)
    stripe_price_id = models.CharField(max_length=100)
    price = models.IntegerField(default=0)
    def get_display_price(self):
        return self.price


class BuyJudge(models.Model):
    stripe_product_id = models.CharField(verbose_name='商品ID', max_length=100)
    stock = models.IntegerField(verbose_name='購入数')
    def __str__(self):
        return self.stripe_product_id


class Payment_intent(models.Model):
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.CASCADE)
    payment_intent = models.CharField(max_length=9999)
    def __str__(self):
        return self.payment_intent

# Create your models here.

purchaseapp/forms.py
from django.forms import ModelForm
from .models import CartPost


class CartPostForm(ModelForm):
    class Meta:
        model = CartPost
        fields = ['stockminus']

    def __init__(self, *args, **kwargs):
        super(CartPostForm, self).__init__(*args, **kwargs)
        maxvalue = kwargs['instance'].stock
        self.fields['stockminus'].widget.attrs.update({
            'class': 'form-control text-center me-3',
            'id': 'inputQuantity',
            'style': 'max-width: 3rem',
            'type': 'number',
            'min': 1,
            'max': maxvalue
        })

purchaseapp/templates/buy.html
{% extends 'base.html' %}
{% block title %}商品詳細{% endblock %}
{% block content %}
{% if object %}
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{ object.image.url }}" alt="..." style="width: 100%; height: 100%" /></div>
            <div class="col-md-6">
                <h1 class="display-5 fw-bolder">{{ object.name }}</h1>
                <style>
                    form input[type="number"]::-webkit-outer-spin-button,
                    form input[type="number"]::-webkit-inner-spin-button {
                        -webkit-appearance: none !important;
                        margin: 0 !important;
                        appearance: none !important;
                    }

                    form input[type="number"] {
                        -moz-appearance: textfield !important;
                        appearance: none !important;
                    }

                    .select1 {
                        padding-top: 5px;
                        padding-bottom: 5px;
                    }
                </style>
                <form action="{% url 'purchaseapp:buysuccess' object.stripe_product_id %}" method="POST" onsubmit="cartinput()">
                    <p class="lead">値段　　　　　<span class="fs-5">￥{{ object.price }}</span></p>
                    <p class="lead">賞味期限　　　<span class="fs-5">{{ object.shelf_life }}</span></p>
                    <p class="lead">アレルギー　　{{ object.allergy }}</p>
                    <p class="lead">カテゴリー　　{{ object.category }}</p>
                    <div class="d-flex mb-3">
                        <p class="lead">数量　　　　　</p>
                        <select name="addstock" class="select1">
                            {% for num in numlist %}
                            <option value="{{ num }}">{{ num }}
                            {% endfor %}
                        </select>
                    </div>
                    {% csrf_token %}
                    <div class="d-flex">
                        <button class="btn btn-outline-primary flex-shrink-0 mt-0 w-50" type="submit">
                            <i class="bi-cart-fill me-1"></i>カートに入れる
                        </button>
                        <a href="{% url 'index' %}"class="btn btn-secondary mx-3 my-2">キャンセル</a>
                    </div>
                    <p>在庫数：{{ maxnum }}</p>
                </form>
            </div>
        </div>
    </div>
</section>
{% else %}
<br><br>
<div style="text-align: center">
    <h3>商品がありません</h3>
</div>
<br>
<div class="text-center"><a class="btn btn-secondary my-2" onclick="location.href='{% url 'dgroupapp:index' %}'">トップページに戻る</a></div>
<br>
{% endif %}
{% if user.is_authenticated %}
<script>
    function cartinput(){
        alert('買い物かごに追加しました')
    }
</script>
{% endif %}
{% endblock %}

purchaseapp/templates/cancel.html
{% extends 'base.html' %}
{% block title %}キャンセル{% endblock %}
{% block content %}
<section>
    <p><a href="{% url 'index' %}">トップページに戻る</a></p>
</section>
{% endblock %}

purchaseapp/templates/cart.html
{% extends 'base.html' %}
{% block title %}買い物かご{% endblock %}

{% block content %}
<!-- Header-->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder"><font color="white">買い物かご</font></h1>
        </div>
    </div>
</header>
<section class="py-5">
    <style>
        .input_btn {
            background-color: #0d6efd;
            color: white;
            padding: 11.5px 16px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 14px;
            margin-right: 10px;
            margin-bottom: 10px;
        }

        .input_btn:hover {
            background-color: #0b5ed7;
            color: white;
        }
    </style>
    {% if object_list.count == 0 %}
    <div style="text-align: center">
        <h3>買い物かごに商品がありません</h3>
        <a href="{% url 'index' %}" class="btn btn-secondary mt-4">買い物を続ける</a>
    </div>
    {% else %}
    {% if errorname_list %}
    <div style="text-align: center">
        <p><font color="red">在庫が不足しています</font></p>
    </div>
    {% endif %}
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-1 row-cols-min-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% for record in object_list %}
                {% if record.stripe_product_id in errorname_list %}
                    {% for i in error_list %}
                        {% if i.0 == record.stripe_product_id %}
                        <div class="col mb-5">
                            <div class="card h-100">
                                <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem; background-color: red !important">数量:{{ record.stock }}</div>
                                <!-- Product image-->
                                <img src="{{ record.aitemimage.url }}" class="card-img-top" height="150px" />
                                <!-- Product details-->
                                <div class="card-body p-4">
                                    <div class="text-center">
                                        <!-- Product name-->
                                        <h5 class="fw-bolder">{{ record.aitemname }}</h5>
                                        <!-- Product price-->
                                        <span class="price">￥{{ record.price }}</span><br>
                                        <span class="shelf">賞味期限<br>{{ record.shelf }}</span>
                                    </div>
                                </div>
                                <!-- Product actions-->
                                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                    <form method="POST">
                                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" onclick="location.href='{% url 'purchaseapp:over' record.pk %}'">詳細・数量変更</a></div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    {% endfor %}
                {% else %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">数量:{{ record.stock }}</div>
                            <!-- Product image-->
                            <img src="{{ record.aitemimage.url }}" class="card-img-top" height="150px" />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ record.aitemname }}</h5>
                                    <!-- Product price-->
                                    <span class="price">￥{{ record.price }}</span><br>
                                    <span class="shelf">賞味期限<br>{{ record.shelf }}</span>
                            </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <form method="POST">
                                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" onclick="location.href='{% url 'purchaseapp:purchase_delete' record.pk %}'">詳細・数量変更</a></div>
                                </form>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
    <div class="text-center"><a class="btn input_btn my-2" onclick="location.href='{% url 'purchaseapp:purchase' user.id %}'">購入</a>
    <a href="{% url 'index' %}"class="btn btn-secondary my-2">トップページに戻る</a>
    </div>
    {% endif %}
</section>
{% endblock %}

purchaseapp/templates/delete.html
{% extends 'base.html' %}
{% block title %}編集{% endblock %}
{% block content %}
    {% if object %}
        <section class="py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="row gx-4 gx-lg-5 align-items-center">
                    <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{ object.aitemimage.url }}" alt="..." style="width: 100%; height: 100%"/></div>
                    <div class="col-md-6">
                        <div style="word-break: break-word; overflow-wrap: break-word;">
                        <h1 class="display-5 fw-bolder">{{ object.aitemname }}</h1>
                        <div class="fs-5 mb-5">
                            <span>￥{{ object.price }}</span>
                        </div>
                        <form action="{% url 'purchaseapp:deletesuccess' object.stripe_product_id %}" method="POST">
                            <table class="lead">
                                <tr>
                                    <td>
                                        賞味期限　　　
                                    </td>
                                    <td>
                                        {{ object.shelf }}
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        アレルギー
                                    </td>
                                    <td>
                                        {{ object.allergy }}
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        カテゴリー
                                    </td>
                                    <td>
                                        {{ object.category }}
                                    </td>
                                </tr>
                            </table>
                            <div class="d-flex">
                                数量　　　　　　　
                                <select name="deletestock" class="select1">
                                    {% for i in deletenumber %}
                                    <option value="{{ i }}">{{ i }}
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="d-flex">
                                {% csrf_token %}
                                <button class="btn input_btn my-2"type="submit">保存</button>
                                　
                                <a href="{% url 'purchaseapp:cart' user.id %}"class="btn btn-secondary my-2">戻る</a>
                            </div>
                        </form>
                        <style>
                            form input[type="number"]::-webkit-outer-spin-button,
                            form input[type="number"]::-webkit-inner-spin-button {
                                -webkit-appearance: none !important;
                                margin: 0 !important;
                                appearance: none !important;
                            }

                            form input[type="number"] {
                                -moz-appearance: textfield !important;
                                appearance: none !important;
                            }
                            .select1 {
                                display: block;
                                width: 20%;
                                padding: 0.375rem 2.25rem 0.375rem 0.75rem;
                                -moz-padding-start: calc(0.75rem - 3px);
                                font-size: 1rem;
                                font-weight: 400;
                                line-height: 1.5;
                                color: #212529;
                                background-color: #fff;
                                background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3e%3cpath fill='none' stroke='%23343a40' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='m2 5 6 6 6-6'/%3e%3c/svg%3e");
                                background-repeat: no-repeat;
                                background-position: right 0.75rem center;
                                background-size: 16px 12px;
                                border: 1px solid #ced4da;
                                border-radius: 0.375rem;
                                transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
                                -webkit-appearance: none;
                                -moz-appearance: none;
                                appearance: none;
                            }

                            .select1:focus{
                                border-color: #86b7fe;
                                outline: 0;
                                box-shadow: 0 0 0 0.25rem rgba(13, 110, 253, 0.25);
                            }
                            .input_btn {
                                background-color: #0d6efd;
                                color: white;
                                padding: 8.5px 16px;
                                border: none;
                                border-radius: 5px;
                                cursor: pointer;
                                font-size: 14px;
                                margin-right: 10px;
                                margin-bottom: 10px;
                            }

                            .input_btn:hover {
                                background-color: #0b5ed7;
                                color: white;
                            }
                        </style>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    {% else %}
    <br><br>
    <div style="text-align: center">
        <h3>商品の有効期限が切れました</h3>
    </div>
    <br>
    <div class="text-center"><a class="btn btn-secondary my-2" onclick="location.href='{% url 'dgroupapp:index' %}'">トップページに戻る</a></div>
    <br>
    {% endif %}
{% endblock %}

purchaseapp/templates/error.html
{% extends 'base.html' %}
{% block title %}{{ object.name }}エラー{% endblock %}
{% block content %}
<br><br>
<div style="text-align: center">
    <h3>商品がありません</h3>
</div>
<br>
<div class="text-center"><a class="btn btn-outline-dark mt-auto" onclick="location.href='{% url 'dgroupapp:index' %}'">トップページに戻る</a></div>
<br>
{% endblock %}

purchaseapp/templates/product-top.html
{% extends 'base.html' %}
{% block title %}商品トップ{% endblock %}
{% block content %}
<session>
    <h1>商品一覧</h1>
    <hr />
        <div clss="product">
            <div class="description">
                {% for product in product_list %}
                    <h2>{{ product.nae }}</h2>
                    <picture>
                        <img src="{{ product.file.url }}" alt="image" style="width:auth;">
                    </picture>
                    <div>{{ product.description }}</div>
                    {% for price_data in product.Prices.all %}
                    <h4>価格:￥{{ price_data.get_display_price }}</h4>
                    <form action="{% url 'create-checkout-session' product.id %}" method="POST">
                        {% csrf_token %}
                        <button type="submit">購入画面に進む</button>
                    </form>
                    {% endfor %}
                {% endfor %}
            </div>
        </div>
</session>
{% endblock %}

purchaseapp/templates/purchase.html
{% extends 'base.html' %}
{% block title %}購入確認{% endblock %}

{% block content %}
{% if object_list %}
<section class="py-5">
    <section class="py-5">
    <style>
        .input_btn {
            background-color: #0d6efd;
            color: white;
            padding: 11.5px 16px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 14px;
            margin-right: 10px;
            margin-bottom: 10px;
        }

        .input_btn:hover {
            background-color: #0b5ed7;
            color: white;
        }
        .form2 {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            text-align: center;
            margin-top: 20px;
        }    
    </style>
    <div style="background-color: white; border: solid 1px white; padding: 1px; border-radius: 10px; margin: 1% 3%; box-shadow: 0 0 8px gray;">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="text-center">
            <table class="purchasetable">
                <tr>
                    <th>商品名</th>
                    <th>価格</th>
                    <th>個数</th>
                    <th></th>
                </tr>
                {% for record in object_list %}
                <tr>
                    <td>{{ record.aitemname }}</td>
                    <td>￥{{ record.price }}</td>
                    <td>{{ record.stock }}</td>
                    <td><a href="{% url 'purchaseapp:detail' record.pk %}">詳細</a>
                    </td>
                </tr>
                {% endfor %}
                {% if totalprice < 1000 %}
                    <tr>
                        <td>送料</td>
                        <td>￥150</td>
                        <td></td>
                        <td></td>
                    </tr>
                {% endif %}
                {% if totalprice < 1000 %}
                <tr>
                    <td>支払額</td>
                    <td>￥{{ totalprice|add:"150" }}</td>
                    <td>{{ totalstock }}</td>
                    <td></td>
                </tr>
                {% else %}
                <tr>
                    <td>支払額</td>
                    <td>￥{{ totalprice }}</td>
                    <td>{{ totalstock }}</td>
                    <td></td>
                </tr>
                {% endif %}
            </table>
        </div>
    </div>
        <br>
        <form action="{% url 'create-checkout-session' %}" method="POST" class="form2">
            <div class="text-align: center">
                {% csrf_token %}
                    <label for="zipcode">郵便番号</label>
                    <input type="text" name="postnumber" id="zipcode" oninput="fetchAddress()" value="{{ user.postal_code }}" style="width: 200px" class="input1" title="郵便番号は7桁の半角数字で入力してください" pattern="^\d{7}$" required>
                    <br>
                    住所
                    <input type="text" name="address" id="address" style="width: 200px" title="長野市篠ノ井地域のみ" pattern=".*長野市篠ノ井.*" class="input1" required>
                    <br>
                    支払方法
                    <select name="payment" id="select" style="width: 200px" class="select1">
                        <option value="0">--------</option>
                        <option value="1">クレジットカード決済</option>
                        <option value="2">代金引換</option>
                    </select>
                <br>
                <div id="message1" class="hidden">
                    <button class="btn input_btn my-2" type="submit" name="credit">購入画面に進む</button>
                    <a href="{% url 'purchaseapp:cart' user.id %}"class="btn btn-secondary my-2">戻る</a>
                </div>

                <div id="message2" class="hidden">
                    <button class="btn input_btn my-2" type="submit" name="cash">購入画面に進む</button>
                    <a href="{% url 'purchaseapp:cart' user.id %}"class="btn btn-secondary my-2">戻る</a>
                </div>

                <div id="message0" class="hidden">
                    <a href="{% url 'purchaseapp:cart' user.id %}"class="btn btn-secondary my-2">戻る</a>
                </div>
                <br>
                <script>
                    const select = document.getElementById("select");
                    const message1 = document.getElementById("message1");
                    const message2 = document.getElementById("message2");
                    const message0 = document.getElementById("message0");
                    message1.classList.add('hidden');
                    message2.classList.add('hidden');
                    message0.classList.remove('hidden')

                    select.addEventListener("change", (event) => {
                        const value = event.target.value;
                        message1.classList.toggle("hidden", value !== "1");
                        message2.classList.toggle("hidden", value !== "2");
                        message0.classList.toggle("hidden", value !== "0");                        
                    });

                    function fetchAddress() {
                        var zipcode = document.getElementById('zipcode').value;
                        if (zipcode.length === 7) {
                            fetch(`https://api.zipaddress.net/?zipcode=${zipcode}`, { mode: 'cors' })
                            .then(response => response.json())
                            .then(data => {
                                if (data.code === 200) {
                                document.getElementById('address').value = data.data.fullAddress;
                                } else {
                                document.getElementById('address').value = '住所が見つかりません';
                                }
                            })
                            .catch(error => console.error('エラーが発生しました:', error));
                        }
                    }

                    window.onload = function(){
                        fetchAddress();
                    };

                </script>
            </div>
        </form>
    </div>
</section>
{% else %}
    <br><br>
    <div style="text-align: center">
        <h3>商品の有効期限が切れました</h3>
    </div>
    <br>
    <div class="text-center"><a class="btn btn-secondary my-2" onclick="location.href='{% url 'dgroupapp:index' %}'">トップページに戻る</a></div>
    <br>
{% endif %}
{% endblock %}

purchaseapp/templates/timeout.html
{% extends 'base.html' %}
{% block title %}エラー{% endblock %}
{% block content %}
決済の有効期限が切れました
{% endblock %}