Dgroupproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from purchaseapp.views import (
    CreateCheckoutSessionView,
    ProductTopPageView,
    PurchaseCheck,
    SuccessPage,
    CancelPageView,
    stripe_webhook,
    cancel_checkout,
)
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dgroupapp.urls')),
    path('', include('purchaseapp.urls')),
    path('', include('delivery.urls')),
    path('', include('foods.urls')),
    path('', include('adminmenu.urls')),
    path('dgroupLogin/', include('dgroupLogin.urls', namespace='dgroupLogin')),
    path('', include('dgrouinquiry.urls')),
    path('stripe/', ProductTopPageView.as_view(), name="product-top-page"),
    path('stripe/create-checkout-session/', CreateCheckoutSessionView.as_view(), name="create-checkout-session"),
    path('stripe/purchasecheck', PurchaseCheck, name='purchasecheck'),
    path('stripe/success/', SuccessPage, name='success'),
    path('stripe/cancel/', cancel_checkout, name="cancel"),
    path('stripe/cancel/template', CancelPageView.as_view(), name='canceltemplate'),
    path('webhook2/', stripe_webhook, name="webhook"),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="pw_reset.html"), name='password_reset'),
    path('password_reset/done', auth_views.PasswordResetDoneView.as_view(template_name="pw_reset_sent.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="pw_reset_form.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="pw_reset_done.html"), name='password_reset_complete'),
]


# urlpatternsにmediaフォルダのURLパターンを追加
urlpatterns += static(
    # MEDIA_URL = 'media/'
    settings.MEDIA_URL,
    # MEDIA_ROOTにリダイレクト
    document_root=settings.MEDIA_ROOT
)

dgroupLogin/urls.py
from django.urls import path
from . import views
from .views import TermsAndPrivacyView

app_name = 'dgroupLogin'

urlpatterns = [
    path('terms-and-privacy/', TermsAndPrivacyView.as_view(), name='terms_and_privacy'),
    path('termsofservice', views.terms_of_service_view, name='termsofservice'),
    path('privacyconfirmation/', views.privacy_confirmation_view, name='privacy_confirmation'),  # 追加
    path('user_profile/', views.user_profile_view, name='user_profile'),
    path('confirmation/', views.confirmation_view, name='confirmation'),
    path('singnup_success/', views.singnup_success_view, name='singnup_success'),
    
]

dgroupapp/urls.py
from django.urls import path,include
from .views import IndexView, LoginView, LogoutView, SuperuserOnlyView
from .import views

app_name = 'dgroupapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('superuser-only/', SuperuserOnlyView.as_view(), name='superuser_only'),
    path('contact/', include('dgrouinquiry.urls')),
    path('switch_account/', views.switch_account, name='switch_account'),
    path('teams/', views.TeamsView.as_view(), name='teams'),  
    path('privacy/', views.PrivacyView.as_view(), name='privacy'),
    path('convenience/', include('Convenience.urls')),
    path('profile/', views.profile, name='profile'),
    path('edit_address/', views.edit_address, name='edit_address'),
    path('address_update_complete/', views.address_update_complete, name='address_update_complete'),
    path('category/<int:category_id>/', views.category_view, name='category_view'),
    path('new-arrivals/', views.NewArrivalsView.as_view(), name='new_arrivals'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('about/', views.AboutView.as_view(), name='about'), 
    
]
#http://127.0.0.1:8000/convenience/register/

foods/urls.py
from django.urls import path
from .import views

app_name = 'foods'

urlpatterns = [
    path('food_input/', views.FoodCreateView.as_view(), name='food_input'),
    path('food_delete/', views.FoodDeleteListView.as_view(), name='food_delete_list'), 
    path('food_delete/<int:pk>/', views.FoodDeleteView.as_view(), name='food_delete'),
    path('food_update/<int:pk>', views.FoodUpdateView.as_view(), name='food_update'),
]

purchaseapp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'purchaseapp'

urlpatterns = [
    path('cart/<int:user>', views.CartView.as_view(), name='cart'),
    path('cart/<int:pk>/delete', views.PurchaseDeleteView.as_view(), name='purchase_delete'),
    path('cart/deletesuccess/<str:stripe_product_id>', views.DeleteSuccess, name="deletesuccess"),
    path('cart/purchase/<int:user>', views.PurchaseView.as_view(), name='purchase'),
    path('cart/<int:pk>/detail', views.DetailView.as_view(), name='detail'),
    path('buy/<int:pk>', views.BuyView.as_view(), name='buy'),
    path('buy/buysuccess/<str:stripe_product_id>', views.BuySuccess, name='buysuccess'),
    path('cart/over/<int:pk>', views.OverView.as_view(), name='over'),
    path('cart/overback', views.Overback, name='overback'),
    path('cart/overdelete/<str:stripe_product_id>', views.OverDelete, name='overdelete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dgroupapp/models.py
from django.db import models

dgroupapp/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator

class AddressEditForm(forms.Form):
    address = forms.CharField(
        max_length=255,
        required=True,
        validators=[RegexValidator(r'^(?!.*住所が見つかりません).*', '正しい住所を表示させてください')],
        error_messages={
            'required': 'お届け先住所を入力してください',
        }
    )
    postal_code = forms.CharField(
        max_length=7,
        min_length=7,
        required=True,
        error_messages={
            'required': '※郵便番号を入力してください',
            'min_length': '※郵便番号は7桁で入力してください',
            'max_length': '※郵便番号は7桁で入力してください',
        },
    )
    
    # 郵便番号のバリデーション（数字だけ）
    def clean_postal_code(self):
        postal_code = self.cleaned_data.get('postal_code')
        if not postal_code.isdigit():
            raise ValidationError('郵便番号は数字だけで入力してください')
        return postal_code

dgroupapp/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView, DeleteView, CreateView
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import UserPassesTestMixin
from foods.models import Food, Category
from dgroupLogin.models import CustomUser 
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from foods.models import Food 
from dgroupLogin.forms import ProfileEditForm
from purchaseapp.models import CartPost, BuyJudge
from .forms import AddressEditForm
from django.core.paginator import Paginator
from django.contrib.auth.hashers import check_password
from django import forms
from django.urls import reverse



class IndexView(ListView):
    model = Food
    template_name = 'index.html'
    context_object_name = 'object_list'

    def get_queryset(self):
        # 先に検索条件でフィルタリング
        queryset = Food.objects.all()

        self.search_query = self.request.GET.get('name', None)
        if self.search_query:
            queryset = queryset.filter(name__icontains=self.search_query)

        # フィルタリング後のデータをそのまま返す
        return queryset.order_by('-inputed_at')  # ページネーションのためスライスはしない

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Paginatorを使用してページネーション
        paginator = Paginator(context['object_list'], 8)  # 1ページあたり8件
        page_number = self.request.GET.get('page')  # URLからページ番号を取得
        page_obj = paginator.get_page(page_number)  # ページネーションされたオブジェクト

        context['object_list'] = page_obj  # ページネーションされたデータ
        context['search_query'] = self.search_query
        context['result_count'] = context['object_list'].paginator.count  # 結果数を表示
        context['categorys'] = Category.objects.all()
        context['recommended_items'] = Food.objects.order_by('shelf_life')[:4]

        # 在庫数の処理（既存コード）
        food_list = [i.stripe_product_id for i in Food.objects.all()]
        minus = []
        target = []
        judge = BuyJudge.objects.all()
        for i in judge:
            if i.stripe_product_id in food_list:
                foodsstock = Food.objects.get(stripe_product_id=i.stripe_product_id)
                stock = foodsstock.stock - i.stock
                if stock < 0:
                    stock = 0
                minus.append([i.stripe_product_id, stock])
                target.append(i.stripe_product_id)
        
        context['minus'] = minus
        context['target'] = target

        return context

    def get_template_names(self):
        if self.request.GET.get('name'):
            return ['search.html']
        return ['index.html']

class LoginView(TemplateView):
    template_name = 'login.html'

    def get(self, request):
        form = AuthenticationForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data['username'],
                                password=form.cleaned_data['password'])
            if user is not None:
                login(request, user)
                return redirect('dgroupapp:index')  # アプリ名を含める
        return render(request, self.template_name, {'form': form})


class LogoutView(TemplateView):
    template_name = 'logout.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        logout(request)
        return redirect('dgroupapp:index')  # ログアウト後にリダイレクトするURL


class SuperuserOnlyView(UserPassesTestMixin, TemplateView):
    template_name = 'system_menu.html'

    def test_func(self):
        return self.request.user.is_superuser


# 利用規約
class TeamsView(TemplateView):
    template_name = 'teams.html'


class PrivacyView(TemplateView):
    template_name = 'privacy.html'


@login_required
def switch_account(request):
    class PasswordForm(forms.Form):
        password = forms.CharField(widget=forms.PasswordInput, label='Password')

    if request.method == 'POST':
        # ユーザーIDとパスワードを取得
        user_id = request.POST.get('user_id')
        password = request.POST.get('password')

        try:
            user = CustomUser.objects.get(id=user_id)

            # ログイン中のユーザーと選択したユーザーのメールアドレスが一致するかを確認
            if user.email == request.user.email:
                # 入力されたパスワードがユーザーのパスワードと一致するか確認
                if check_password(password, user.password):
                    login(request, user)  # パスワードが一致すれば切り替え
                    return redirect('dgroupapp:index')  # インデックスページへリダイレクト
                else:
                    # パスワードが間違っている場合、元のページに戻す
                    messages.error(request, "パスワードが間違っています。")
                    return redirect(reverse('dgroupapp:switch_account'))  # 元のページに戻る
            else:
                messages.error(request, "このアカウントは切り替えられません。")
                return redirect(reverse('dgroupapp:switch_account'))  # 元のページに戻る

        except CustomUser.DoesNotExist:
            messages.error(request, "指定されたユーザーが見つかりません。")
            return redirect(reverse('dgroupapp:switch_account'))  # 元のページに戻る

    else:
        # 自分と同じメールアドレスを持つユーザーのみ表示
        users = CustomUser.objects.filter(email=request.user.email)
        password_form = PasswordForm()
        return render(request, 'switch_account.html', {'users': users, 'password_form': password_form})
@login_required
def profile(request):
    return render(request, 'profile.html', {'user': request.user})


@login_required
def edit_address(request):
    if request.method == 'POST':
        form = AddressEditForm(request.POST)
        
        if form.is_valid():
            # フォームがバリデーションを通過した場合、ユーザーの住所を更新
            new_address = form.cleaned_data['address']
            new_postal_code = form.cleaned_data['postal_code']
            
            request.user.address = new_address
            request.user.postal_code = new_postal_code
            request.user.save()

            return redirect('dgroupapp:address_update_complete')
        else:
            # フォームが無効な場合、エラーメッセージを表示
            return render(request, 'edit_address.html', {'form': form})
    
    # GETリクエストの場合、フォームを空で表示
    form = AddressEditForm(initial={
        'address': request.user.address,
        'postal_code': request.user.postal_code
    })
    return render(request, 'edit_address.html', {'form': form})

@login_required
def address_update_complete(request):
    return render(request, 'address_update_complete.html')


def category_view(request, category_id):
    category = Category.objects.get(id=category_id)
    products = Food.objects.filter(category=category)

    # 在庫数の処理
    food_list = [i.stripe_product_id for i in products]
    minus = []
    target = []
    judge = BuyJudge.objects.all()
    for i in judge:
        if i.stripe_product_id in food_list:
            foodsstock = Food.objects.get(stripe_product_id=i.stripe_product_id)
            stock = foodsstock.stock - i.stock
            if stock < 0:
                stock = 0
            minus.append([i.stripe_product_id, stock])
            target.append(i.stripe_product_id)

    # Paginatorで商品を8件ずつ分割
    paginator = Paginator(products, 8)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    categories = Category.objects.all()  # 全カテゴリ情報を取得
    return render(request, 'category_view.html', {
        'category': category,
        'products': page_obj,  # ページネーションされた商品を渡す
        'categorys': categories,  # カテゴリ情報をテンプレートに渡す
        'minus': minus,  # 在庫数の減少リストを渡す
        'target': target,  # 在庫数が変更された商品のリストを渡す
    })

class NewArrivalsView(ListView):
    model = Food
    template_name = 'new_arrivals.html'
    context_object_name = 'new_arrivals'

    def get_queryset(self):
        # 新着商品を新着順で取得
        return Food.objects.order_by('-inputed_at')  # 新着順で並べ替え

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        # 商品リストを取得
        product_list = Food.objects.order_by('-inputed_at')  # 新着順で並べ替え
        
        # Paginatorを使ってページネーション
        paginator = Paginator(product_list, 8)  # 1ページあたり8件を表示
        
        # 現在のページを取得
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        food_list = []
        foods = Food.objects.all()
        for i in foods:
            food_list.append(i.stripe_product_id)
        minus = []
        target = []
        judge = BuyJudge.objects.all()
        for i in judge:
            if i.stripe_product_id in food_list:
                foodsstock = Food.objects.get(stripe_product_id=i.stripe_product_id)
                stock = foodsstock.stock - i.stock
                if stock < 0:
                    stock = 0
                minus.append([i.stripe_product_id, stock])
                target.append(i.stripe_product_id)
        context['minus'] = minus
        context['target'] = target

        context['new_arrivals'] = page_obj  # ページネーションされた商品
        context['categorys'] = Category.objects.all()  # カテゴリ情報も追加
        return context
    
@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = ProfileEditForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('dgroupapp:profile')  # プロフィールページにリダイレクト
    else:
        form = ProfileEditForm(instance=request.user)

    return render(request, 'edit_profile.html', {'form': form})


class AboutView(TemplateView):
    template_name = 'about.html'

dgroupapp/templates/address_update_complete.html
{% extends "base.html" %}

{% block title %}住所更新完了{% endblock %}

{% block content %}
<div class="container custom-completion-container">
    <h3 class="custom-completion-heading">住所更新が完了しました</h3>
    <hr>
    <p class="custom-completion-message">郵便番号:{{ user.postal_code }}</p>
    <p class="custom-completion-message">住所:{{ user.address }}</p>
    <a href="{% url 'index' %}" class="btn btn-primary custom-back-btn">トップページに戻る</a>
</div>
{% endblock %}

dgroupapp/templates/category_view.html
{% extends "base.html" %}
{% load static %}

{% block title %}Waste Not{% endblock %}

{% block content %}
<section>
    <div class="category-header">
        <div class="category-container">
            {% for category in categorys %}
                <div class="category-card">
                    <a href="{% url 'dgroupapp:category_view' category.id %}">
                        <img src="{{ category.image.url }}" alt="カテゴリ画像">
                        <p>{{ category.title }}</p>
                    </a>
                </div>
            {% empty %}
                <p>カテゴリがありません。</p>
            {% endfor %}
        </div>
    </div>
    <div class="container px-4 px-lg-5 mt-1 py-2">
        <div class="search-result">
        <h3 style="text-align: center;">
            ”{{ category.title }}”の検索結果
        </h3>
        </div>

        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 py-3 justify-content-center">
            {% for record in products %}
                {% if record.stripe_product_id in target %}
                    {% for i in minus %}
                    {% if i.0 == record.stripe_product_id %}
                        {% if i.1 > 0 %}
                        <div class="col mb-5">
                            <div class="card h-100">
                                <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">
                                    在庫数:{{ i.1 }}
                                </div>    
                                <!-- 商品画像 -->
                                <img class="card-img-top" src="{{ record.image.url }}" width="100%" height="100%" alt="..." />
                                <!-- 商品詳細 -->
                                <div class="card-body p-4">
                                    <div class="text-center">
                                        <h5 class="fw-bolder">{{ record.name }}</h5>
                                        <span class="price">￥{{ record.price }}</span><br>
                                        <span class="shelf">賞味期限<br>{{ record.shelf_life }}</span>
                                    </div>
                                </div>
                                <!-- 商品アクション -->
                                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                    <div class="text-center">
                                        <a class="btn btn-outline-dark mt-auto" href="{% url 'purchaseapp:buy' record.pk %}">商品詳細</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% else %}
                        
                        {% endif %}
                    {% endif %}
                    {% endfor %}
                
                {% else %}
                <div class="col mb-5">
                    <div class="card h-100">
                        <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">
                            在庫数:{{ record.stock }}
                        </div>    
                        <!-- 商品画像 -->
                        <img class="card-img-top" src="{{ record.image.url }}" width="100%" height="100%" alt="..." />
                        <!-- 商品詳細 -->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <h5 class="fw-bolder">{{ record.name }}</h5>
                                <span class="price">￥{{ record.price }}</span><br>
                                <span class="shelf">賞味期限<br>{{ record.shelf_life }}</span>
                            </div>
                        </div>
                        <!-- 商品アクション -->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center">
                                <a class="btn btn-outline-dark mt-auto" href="{% url 'purchaseapp:buy' record.pk %}">商品詳細</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
            {% endfor %}
        </div>

<!-- ページネーション -->
<div class="pagination-container">
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center flex-wrap">
            {% if products.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ products.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link" aria-hidden="true">&laquo;</span>
            </li>
            {% endif %}

            {% for page_num in products.paginator.page_range %}
            <li class="page-item {% if products.number == page_num %}active{% endif %}">
                <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
            </li>
            {% endfor %}

            {% if products.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ products.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link" aria-hidden="true">&raquo;</span>
            </li>
            {% endif %}
        </ul>
    </nav>
</div>

</div>

</section>
{% endblock %}

dgroupapp/templates/new_arrivals.html
{% extends "base.html" %}

{% block title %}新着商品{% endblock %}

{% block content %}

<div class="category-header">
    <div class="category-container">
        {% for category in categorys %}
            <div class="category-card">
                <a href="{% url 'dgroupapp:category_view' category.id %}">
                    <img src="{{ category.image.url }}" alt="カテゴリ画像">
                    <p>{{ category.title }}</p>
                </a>
            </div>
        {% empty %}
            <p>カテゴリがありません。</p>
        {% endfor %}
    </div>
</div>
<!-- 新着商品の表示 -->
<div class="container px-4 px-lg-5 mt-1">
    <h2 class="section-title">- 商品一覧 -</h2>
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        {% for record in new_arrivals %}
            {% if record.stripe_product_id in target %}
                {% for i in minus %}
                {% if i.0 == record.stripe_product_id %}
                    {% if i.1 > 0 %}
                    <!-- 商品カード -->
                    <div class="col mb-5">
                        <div class="card h-100">
                            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">
                                在庫数:{{ i.1 }}
                            </div>
                            <img class="card-img-top" src="{{ record.image.url }}" alt="{{ record.name }}" />
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <h5 class="fw-bolder">{{ record.name }}</h5>
                                    <span class="price">￥{{ record.price }}</span><br>
                                    <span class="shelf">賞味期限<br>{{ record.shelf_life }}</span>
                                </div>
                            </div>
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center">
                                    <a class="btn btn-outline-dark mt-auto" href="{% url 'purchaseapp:buy' record.pk %}">商品詳細</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% else %}

                    {% endif %}
                {% endif %}
                {% endfor %}

            {% else %}
            <div class="col mb-5">
                <div class="card h-100">
                    <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">
                        在庫数:{{ record.stock }}
                    </div>
                    <img class="card-img-top" src="{{ record.image.url }}" alt="{{ record.name }}" />
                    <div class="card-body p-4">
                        <div class="text-center">
                            <h5 class="fw-bolder">{{ record.name }}</h5>
                            <span class="price">￥{{ record.price }}</span><br>
                            <span class="shelf">賞味期限<br>{{ record.shelf_life }}</span>
                        </div>
                    </div>
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center">
                            <a class="btn btn-outline-dark mt-auto" href="{% url 'purchaseapp:buy' record.pk %}">商品詳細</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
        {% endfor %}
    </div>

    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            <!-- 前のページ -->
            {% if new_arrivals.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ new_arrivals.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link" aria-hidden="true">&laquo;</span>
            </li>
            {% endif %}
    
            <!-- ページ番号 -->
            {% for page_num in new_arrivals.paginator.page_range %}
            <li class="page-item {% if new_arrivals.number == page_num %}active{% endif %}">
                <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
            </li>
            {% endfor %}
    
            <!-- 次のページ -->
            {% if new_arrivals.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ new_arrivals.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link" aria-hidden="true">&raquo;</span>
            </li>
            {% endif %}
        </ul>
    </nav>
    
</div>


    
    
</div>
    </div>
{% endblock %}

dgroupapp/templates/profile.html
{% extends "base.html" %}

{% block title %}プロフィール{% endblock %}

{% block content %}


<hr>
<div class="profile-info">
    <h3>プロフィール情報</h3>
    <p><strong>ユーザー名:</strong> {{ user.username }}</p>
    <p><strong>ニックネーム:</strong> {{ user.nickname }}</p>
    <p><strong>メールアドレス:</strong> {{ user.email }}</p>
    <p><strong>電話番号:</strong> {{ user.phone_number }}</p>
    <p><strong>郵便番号:</strong> {{ user.postal_code }}</p>
    <p><strong>住所:</strong> {{ user.address }}</p>
</div>


<!-- ボタンを囲むコンテナ -->
<div class="button-container">
    <a href="{% url 'dgroupapp:edit_profile' %}" class="profile-btn">プロフィール編集</a>
    <a href="{% url 'index' %}" class="profile2-btn">トップページに戻る</a>
</div>


{% endblock %}